version: '3.8'
services:
  db:
    image: postgres:15
    container_name: wallet_db
    env_file:
      - .env-non-dev
  wallet_app:
    image: wallet_image
    container_name: wallet_app
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      - .env-non-dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000"